version: "3.7"

services:
  fairseq:
    build: .
    stdin_open: true 
    tty: true        
    # ports:
      # - "80:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
      # mode: replicated
      # replicas: 5
    # environment:
    #   - GPU_DEVICE_ID=0
    
